--CREAR ESQUEMA DE BASE DE DATOS DESARROLLO
CREATE DATABASE db_desarrollo;

--CREATE USER dbuser;
CREATE USER desarrollo;

--grant usage on *.* to user@localhost identified by 'password';
GRANT USAGE ON *.* TO desarrollo@'%' IDENTIFIED BY 'desarrollo';

--grant all privileges on dbname.* to user@localhost;	
GRANT ALL PRIVILEGES ON db_desarrollo.* to desarrollo@'%';

FLUSH PRIVILEGES;

DROP TABLE IF EXISTS CATEGORIA;

CREATE TABLE CATEGORIA(
CATEGORIA_ID INT NOT NULL AUTO_INCREMENT,
NOMBRE VARCHAR(64) NOT NULL,
 CONSTRAINT CATEGORIAPK PRIMARY KEY (CATEGORIA_ID) 
 );

DROP TABLE IF EXISTS PRODUCTO;

CREATE TABLE IF NOT EXISTS PRODUCTO(
PRODUCTO_ID INT NOT NULL AUTO_INCREMENT,
CATEGORIA_ID INT NOT NULL,
NOMBRE VARCHAR(64) NULL,
PRECIO VARCHAR(64) NULL,
STOCK VARCHAR(64) NULL,
CONSTRAINT PRODUCTOPK PRIMARY KEY (PRODUCTO_ID) 
 );

ALTER TABLE PRODUCTO ADD CONSTRAINT CATFKPRO FOREIGN KEY (CATEGORIA_ID) REFERENCES CATEGORIA(CATEGORIA_ID);

INSERT CATEGORIA (NOMBRE) VALUES ('Automovil');

INSERT CATEGORIA (NOMBRE) VALUES ('Hogar');

INSERT CATEGORIA (NOMBRE) VALUES ('Electronica');

COMMIT;

SELECT * FROM CATEGORIA;

INSERT PRODUCTO (CATEGORIA_ID, NOMBRE, PRECIO, STOCK) VALUES (2, 'platos', 20, 5);

INSERT PRODUCTO (CATEGORIA_ID, NOMBRE, PRECIO, STOCK) VALUES (2, 'vasos', 10, 10);

INSERT PRODUCTO (CATEGORIA_ID, NOMBRE, PRECIO, STOCK) VALUES (2, 'ollas', 50, 15);

INSERT PRODUCTO (CATEGORIA_ID, NOMBRE, PRECIO, STOCK) VALUES (2, 'platos', 20, 5);

INSERT PRODUCTO (CATEGORIA_ID, NOMBRE, PRECIO, STOCK) VALUES (3, 'television', 300, 10);

INSERT PRODUCTO (CATEGORIA_ID, NOMBRE, PRECIO, STOCK) VALUES (3, 'dvd', 100, 10);

SELECT * FROM PRODUCTO WHERE CATEGORIA_ID = 2;