--CREACION DE TABLA TIPO_USUARIO
DROP TABLE TIPO_USUARIO;
CREATE TABLE TIPO_USUARIO(
TIPO_USUARIO_ID INT NOT NULL AUTO_INCREMENT,
NOMBRE VARCHAR(256) NOT NULL,
DESCRIPCION VARCHAR(256),
CONSTRAINT PKTIPUSU PRIMARY KEY (TIPO_USUARIO_ID)
);

DROP TABLE USUARIO;
CREATE TABLE USUARIO(
USUARIO_ID INT NOT NULL AUTO_INCREMENT,
TIPO_USUARIO_ID INT  NOT NULL,
NOMBRE VARCHAR(256) NOT NULL,
APELLIDO VARCHAR(256) NOT NULL,
DIRECCION VARCHAR(256),
E_MAIL VARCHAR(256),
TELEFONO VARCHAR(32),
PASS VARCHAR(256) NOT NULL,
CONSTRAINT USUARIOPK PRIMARY KEY (USUARIO_ID)
);

ALTER TABLE USUARIO ADD CONSTRAINT TIPUSUFKUSU FOREIGN KEY (TIPO_USUARIO_ID) REFERENCES TIPO_USUARIO(TIPO_USUARIO_ID);


INSERT INTO TIPO_USUARIO (NOMBRE) VALUES('administrador');
INSERT INTO TIPO_USUARIO (NOMBRE) VALUES('alumno');
INSERT INTO TIPO_USUARIO (NOMBRE) VALUES('profesor');

INSERT INTO USUARIO (TIPO_USUARIO_ID, NOMBRE, APELLIDO, DIRECCION, PASS) VALUES(2,'Santiago','Escudero', 'Jauja','Sam');
INSERT INTO USUARIO (TIPO_USUARIO_ID, NOMBRE, APELLIDO, DIRECCION, PASS) VALUES(2,'Jerome','de la torre', 'conocoto','Jerome');
INSERT INTO USUARIO (TIPO_USUARIO_ID, NOMBRE, APELLIDO, DIRECCION, PASS) VALUES(1,'Silvia','Torres', 'ronda','Silvia');
INSERT INTO USUARIO (TIPO_USUARIO_ID, NOMBRE, APELLIDO, DIRECCION, PASS) VALUES(2,'Cristina','Rosero', 'labrador','Cristina');

SELECT *
FROM USUARIO;

SELECT *
FROM TIPO_USUARIO;
